### PR TITLE
feat: Added keepRelationFields option

### PR DESCRIPTION
**Pull request by alexandrtovmach**
Adding another option to be able to skip relations in resulting schema. It can be useful for cases, when generated JSON schema used to validate request body. For example:

```prisma
generator jsonSchema {
  provider                 = "prisma-json-schema-generator"
  keepRelationScalarFields = "true"
  keepRelationFields       = "false"
}

model User {
  id       String      @id @default(uuid())
  name     String
  role_id  String
  role     Role        @relation(fields: [role_id], references: [id], onDelete: NoAction, onUpdate: NoAction)

  @@map("users")
}

model Role {
  id    String @id @default(uuid())
  label String
  users User[]

  @@map("roles")
}
```
will be converted to:
```js
{
    $schema: 'http://json-schema.org/draft-07/schema#',
    definitions: {
        User: {
            properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                role_id: { type: 'string', },
            },
            type: 'object',
        },
        Role: {
            properties: {
                id: { type: 'string' },
                label: { type: 'string' },
            },
            type: 'object',
        },
    }
}
```

This schema can be used to validate incoming body:
```json
{
  "name": "Alex",
  "role_id": "role_1"
}
```

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@valentinpalkovic thanks for this great tool. Actively using it now, and found valuable feature. Please take a look

**Comment by alexandrtovmach** [comment]
It's not change default behavior, but allow to customize outpur

**Comment by alexandrtovmach** [comment]
@valentinpalkovic any thoughts?

**Comment by valentinpalkovic** [comment]
Thank you for the reminder! I will take a look tomorrow :)

**Review by valentinpalkovic — APPROVED** [review]

**Comment by valentinpalkovic** [comment]
LGTM!

**Comment by alexandrtovmach** [comment]
missed one case, with many-to-one relation field, will try to manage it over weekend and prepare new PR

**Pull request merged**
