### PR TITLE
feat: add required properties array

### PR DESCRIPTION
**Pull request by nklisch**
I have made the requested changes listed in [PR](https://github.com/valentinpalkovic/prisma-json-schema-generator/pull/578) , let me know if there are any issues or other updates needed.

### CODE REVIEW

**Comment by valentinpalkovic** [comment]
@nklisch Thank you for the adjustments. There are still two small prettier issues left. After they are fixed, let's merge this!

Locally, you could run `npm run lint` to find the issues.

**Comment by nklisch** [comment]
linting has been updated!

**Comment by valentinpalkovic** [comment]
fixes #577

**Comment by valentinpalkovic** [comment]
@nklisch Thank you very much for your contribution! 🥳

**Pull request merged**
